### ISSUE TITLE
createGenerateId is undefined after import {createGenerateId} from 'react-jss

### ISSUE THREAD

**Issue by pricetula** [cssinjs/jss#1108]
__Expected behavior:__
Expected createGenerateId to be a function as shown on the documentation const generateId = createGenerateId(). This is after ```import {createGenerateId} from 'react-jss'```

__Describe the bug:__
createGenerateId is undefined

__Versions (please complete the following information):__
 - jss: 8.6.1
 - Browser [e.g. chrome, safari]: Chrome version 74.0.3729.157
 - OS [e.g. Windows, macOS]: Ubuntu

**Comment by chrisands** [comment]
@pricetula you should use `createGenerateClassName` or try alpha version of jss
> https://cssinjs.org/migrations?v=v10.0.0-alpha.16
Due to the fact, that we now use the same ID generator function for both class names and keyframes ID, we had to rename functions `createGenerateClassName` and `generateClassName` to `createGenerateId` and `generateId`.

**Comment by HenriBeck** [comment]
@chrisands thanks for the good response 👍
