### ISSUE TITLE
jss-plugin-vendor-prefixer prefixes CSS custom properties

### ISSUE THREAD

**Issue by rafamel** [cssinjs/jss#1113]
__Expected behavior:__
`jss-plugin-vendor-prefixer` produces `-webkit---padding-start: 0';` for `--padding-start: 0`. This style should be left as is: it is not `padding-start`, but `--padding-start`, an Ionic Framework variable (otherwise it would be easy enough to use a different variable name to not run into this issue).

__Describe the bug:__
`jss-plugin-vendor-prefixer` should only prefix exact matches and correctly detect when things like `--padding-start` are set instead of `padding-start`.

__Versions:__
 - jss: 10.0.0-alpha.16
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: macOS

**Comment by AleshaOleg** [comment]
@rafamel thanks for reporting.

**Comment by AleshaOleg** [comment]
Here as the last instance for unsupported properties we prefixing them with `-webkit-` prefix (who knows maybe with `-webkit-` this value will work).

Here is a case - https://github.com/cssinjs/css-vendor/pull/84 and I don't know many cases exist at all.

That's why we're prefixing with `-webkit-` by default. For now, we're not checking properties if they exist or not.

I'll think tomorrow if I can move `backdrop-filter` prefixing out of `prefixed` plugin. Will test, and probably, we can return unsupported values as they're.

**Comment by kof** [comment]
@AleshaOleg I think you misunderstood the issue, `--padding-start` is a css custom prop, it should never be prefixed (two dashes in the beginning)

**Comment by rafamel** [comment]
@kof exactly. If it starts with two dashes it should not be prefixed as a fallback in any case, @AleshaOleg . Thank you both for the quick response!

**Comment by kof** [comment]
I think we released the fix already

**Comment by AleshaOleg** [comment]
@kof yes, forgot to write fix version here. Fixed in `2.0.4`.
