### ISSUE TITLE
export 'SheetsManager' was not found in 'jss'

### ISSUE THREAD

**Issue by alex-shamshurin** [cssinjs/jss#1131]
Incorrect import of SheetsManager in react-jss in 10.0.0-alpa-17

**Comment by HenriBeck** [comment]
Can you please provide some more info about the issue.

Preferably even a codesandbox

**Comment by pkmnct** [comment]
I am also running into this issue. I believe it is due to one of my project's dependencies (Material UI v3) having a dependency of JSS v9, while I was attempting to update the rest of my project to JSS v10.

If you are running into this issue, run `npm ls jss` to list any dependencies that depend on JSS, and upgrade those dependencies if possible.

**Comment by alex-shamshurin** [comment]
I tried JSS on old project without material-ui. I just Istalled react-jss and got the error. It might be `export 'anything' was not found in 'jss'`, not only SheetsManager. So i decided to use { makeStyles } from material-ui without material components in project. It works.

**Comment by kevinludwig** [comment]
I am seeing the same warning with 10.0.0 and `npm ls jss` shows only 10.0.0 in use. I was trying to upgrade from 8.x of react-jss.

**Comment by HenriBeck** [comment]
@kevinludwig could you please add more information

**Comment by kevinludwig** [comment]
This was a mistake in my webpack file, and I'm not entirely sure what in JSS 10 broke my build. I was doing something like 

```
resolve: {
    modules: ["./src", "./node_modules"]
}
```

So that I could do things like

```
import MyComponent from 'components/MyComponent';
```

This was _maybe_ normal in webpack 3.x and I didn't notice the alias feature in webpack 4. Anyway when I changed this (which was totally not obvious to find) the JSS errors went away.

**Comment by HenriBeck** [comment]
@kevinludwig Could it be that you have a `src/jss.js` file which was then used by webpack to resolve any references to `jss`?

**Comment by codler** [comment]
@HenriBeck I got the same error ` "export 'SheetsManager' was not found in 'jss'` Im using 10.0.0 and this started after I set in tsconfig.json

     "baseUrl": "src"

**Comment by alex-shamshurin** [comment]
Check that you do not have "modules" under "resolve" in your webpack config. Remove it.

**Comment by codler** [comment]
@alex-shamshurin Im using [Create React App](https://create-react-app.dev/)

**Comment by HenriBeck** [comment]
@codler I doubt this is an issue of `jss` but instead connected to your configuration.

**Comment by alex-shamshurin** [comment]
No, just try it.

**Comment by codler** [comment]
It is an issue in `jss`

**Comment by HenriBeck** [comment]
Then please provide a reproducible codesandbox

**Comment by amagee** [comment]
For what it's worth, I had the same issue when I had a `webpack.config.js` that looked like this:

```
module.exports = {
  // ...
  resolve: {
    // ...
    modules: ["src", "node_modules"]
  }
}
```

and it went away when I changed it to this:

```
const path = require('path');
module.exports = {
  // ...
  resolve: {
    // ...
    modules: [path.resolve(__dirname, 'src'), "node_modules"]
  }
}
```
