### ISSUE TITLE
Media query does not get applied because of function value in normal class style

### ISSUE THREAD

**Issue by seanyu4296** [cssinjs/jss#1282]
__Expected behavior:__
I think the expected behavior is that the media query style will apply.

__Describe the bug:__
Media query style does not apply. I think because it created a new class for it maybe because it is a dynamic style?

__Codesandbox link:__ 
https://codesandbox.io/s/pedantic-johnson-5iedy?fontsize=14&hidenavigation=1&theme=dark
https://codesandbox.io/embed/pedantic-johnson-5iedy?fontsize=14&hidenavigation=1&theme=dark

__Versions (please complete the following information):__
 - jss: 10.0.4
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: macOS
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by nico-w** [comment]
I took a look into your CodeSandbox and it really looked like this is expected behavior at the moment - is it a bug? I'm not sure ... According to the documentation **it could be** that this is the expected behavior.

> Static properties being rendered first so that function values will have higher source order specificity.

See here: https://cssinjs.org/react-jss?v=v10.0.4#dynamic-values

Try this CodeSandbox to prove my assumption:
https://codesandbox.io/s/mystifying-bash-eijvf

**Comment by seanyu4296** [comment]
gotcha! since it is expected behavior ill close this.  Thanks! @nico-w
