### ISSUE TITLE
[cssinjs] Site anchors don't scroll properly

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#439]
For e.g. if you open the site with a hash http://cssinjs.org/json-api?v=v6.4.0#font-face

cc @typical000

**Comment by typical000** [comment]
Hi! 
The problem was that all markdown content wasn't already parsed and rendered when we start scrolling.
Just moved `ScrollToHash` from `MdContent` to child component - `HighlightedMarkdown`
Also removed isReady property, because content is always available.

Created PR - https://github.com/cssinjs/cssinjs/pull/12

**Comment by kof** [comment]
tried, your fix, still doesn'T work for me locally

**Comment by kof** [comment]
fixed
