### ISSUE TITLE
[jss-vendor-prefixer] Browser support option

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/jss#518]
It would be great to document the browser support that this plugin is prefixing for.
Also, I couldn't find an option to change that list of browser support.
For instance, it seems that the flexbox property isn't prefixed while UC browser for Android needs it and represent [8.95% of the market share](http://caniuse.com/#search=flexbox).

We have [an open issue](https://github.com/callemall/material-ui/issues/7124) raising that point for the next branch of Material-UI that is using JSS. Here is how [we are handling the issue](https://github.com/callemall/material-ui/blob/master/scripts/prefixGenerator.js) with the master branch thanks to [inline-style-prefixer](https://github.com/rofrischmann/inline-style-prefixer).

**Comment by kof** [comment]
It doesn't need a list of browsers because it is feature detection based. Means it will add a prefix if it is required. Current version of it is very basic, @cvle is working for quite some time now on a new version https://github.com/cssinjs/css-vendor which is fully compatible with postcss autoprefixer.

**Comment by kof** [comment]
Actually for the SSR we still need to think of static prefixing, because detection won't work and then we actually can use that list.

**Comment by oliviertassinari** [comment]
> It doesn't need a list of browsers because it is feature detection based. 

How, I didn't know that! Is this documented, that sounds great. I guess we could provide the user-agent for the server side rendering in order to fully support it.

**Comment by oliviertassinari** [comment]
Still, the downside of a user-agent based solution over a static prefixing is around the caching strategy. You need way more space, or a way to access the internal representation used by the prefixer.

**Comment by kof** [comment]
Feature detection means it tests if browser really supports a particular property, so agent string is not used. For the server we can use any static prefixer including original autoprefixer.

**Comment by oliviertassinari** [comment]
> Feature detection means it tests if browser really supports a particular property

Oh, my bad!

**Comment by kof** [comment]
I would tend to use original autoprefixer on the server because we try to maintain consistency between the css-vendor package and autoprefixer and there are a lot of corner cases with rarely used properties which might be differently handled by different prefixes. In fact @cvle was fixing autoprefixer along the way)

**Comment by kof** [comment]
I think this was just a question, closing it.
