### ISSUE TITLE
[jss-expand] Make it produce arrays based syntax

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#606]
Me and @AleshaOleg are working on last issues with the new css-vendor and we need to vendor prefix compound values e.g. #300. We would need to parse string values otherwise to add prefixes, so now it is easier to deoptimize a bit jss-expand to the jss core array based syntax in order to get the benefits in jss-vendor prefixer.

Example:
```js
transition: ['transform', '1s', 'cubic-bezier(0.23, 1, 0.32, 1)']
```
should result in

```js
transition: [['transform', '1s', 'cubic-bezier(0.23, 1, 0.32, 1)']]
```
in order to let vendor prefixer to produce

```js
transition: [['-webkit-transform', '1s', 'cubic-bezier(0.23, 1, 0.32, 1)']]
```

**Comment by kof** [comment]
cc @typical000

**Comment by AleshaOleg** [comment]
@typical000 Sure, I will update this on next week. Then we can release a new version of `css-vendor`.

**Comment by AleshaOleg** [comment]
Sorry, for long delay:) I did a support for array values in https://github.com/cssinjs/css-vendor/pull/34

@kof, Am I did it right? [There](https://github.com/cssinjs/css-vendor/blob/c316dc0fbd4d17fb1c33e9bafd92dc070598a44f/src/index.test.js#L82) is a test for this.

**Comment by kof** [comment]
Check out [docs](http://cssinjs.org/json-api?v=v9.3.3#alternative-syntax-for-space-and-comma-separated-values)

Core JSS supports

`margin: 10px 20px` => `margin: [['10px', '20px']]`
`border: 1px, 2px` => `border: ['1px', '2px']`

**Comment by AleshaOleg** [comment]
Fixed with https://github.com/cssinjs/css-vendor/pull/34/commits/6efdcb7e2547f046b9c81242e4b8cfb3c49027d5

Example for two dimensional array
Input:
```[['all 100ms ease'], ['transform 200ms linear']]```
Output:
```[['all 100ms ease'], ['-webkit-transform 200ms linear']]```

And for array
Input:
```['all 100ms ease, transform 200ms linear']```
Output:
```['all 100ms ease, -webkit-transform 200ms linear']```

**Comment by AleshaOleg** [comment]
I'm misunderstood cases for array and two dimensional arrays. So, there are 2 case for such kind of situation with arrays (here I wrote 3 - https://github.com/cssinjs/css-vendor/pull/34, the first one is excess, it will not work stably in each case):

1) Simple array:
Input: ['all 100ms ease', 'transform 200ms linear']
Output: ['all 100ms ease', '-webkit-transform 200ms linear']

2) Two dimensional array:
Input: [['all', '100ms', 'ease'], ['transform', '200ms', 'linear']]
Output: [['all', '100ms', 'ease'], ['-webkit-transform', '200ms', 'linear']]

Fixed in https://github.com/cssinjs/css-vendor/pull/34/commits/a342418615f8ee86810827a051e3ef623feefb91

**Comment by AleshaOleg** [comment]
Same as https://github.com/cssinjs/jss/issues/300. Can be closed.

**Comment by kof** [comment]
fixed in jss-vendor-prefixer v1
