### ISSUE TITLE
sheet.addRule() does not update the attached stylesheet...

### ISSUE THREAD

**Issue by thezimmee** [cssinjs/jss#732]
Hello. I'm new to JSS, great work, I'm enjoying using it! I must be doing something wrong, because after attaching a stylesheet I can't add a rule to it (`sheet.addRule(...)`)... nothing seems to work. I've looked at other issues and it seems I've got the right syntax, but I must be missing something. I was able to duplicate this in the code playground here: https://codesandbox.io/s/qqlzmr130q

I appreciate any help. Thank you!

**Comment by kof** [comment]
The reason you don't see it in the style tag is because browsers don't update the representation when a rule is inserted using insertRule API. Its a browser limitation. You can verify it is working if you use it

https://codesandbox.io/s/w28oz957rw

Also you can add a rule before attaching, this will be rendered using textContent then and will be visible.

**Comment by thezimmee** [comment]
Gotcha. Thank you!
