### ISSUE TITLE
When using addRule, the class is applied but the styles are not

### ISSUE THREAD

**Issue by brandondurham** [cssinjs/jss#915]
__Expected behavior:__
After adding a new class with styles using `addRule` I expect to see the element with the new class to be updated with the new styles.

__Describe the bug:__
After creating a new stylesheet and attaching a new class with styles to an element, the class appears on the element but the styles do not.

__Codesandbox link:__ 
https://codesandbox.io/s/00k784vx7l

__Versions (please complete the following information):__
 - jss: v9.8.7
 - Browser: Chrome
 - OS: macOS

**Comment by HenriBeck** [comment]
The problem is that you have a mismatch between your class name which you apply and the one we put into the DOM. If you call `addRule` with a string, this string will only be used as the identifier to get the randomly generated class name from the classes object from the actual stylesheet.

See:
https://codesandbox.io/s/x7xk082w8p

**Comment by brandondurham** [comment]
Sheesh. How did I miss that. Thank you!
